spring:
  application:
    name: xiaobai-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        #配置Sentin dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719
  #消费者将去访问的微服务名称
  server-url:
    nacos-user-service: http://nacos-payment-provider
#      datasource:
#        ds1:
#          nacos:
#            server-addr: localhost:8848
#            dataId: cloudalibaba-sentinel-service
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow   持久化配置
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: '*'